// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Returns a 404 JSON response for unmatched routes.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Server"
                ],
                "summary": "Unmatched path handler",
                "responses": {
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/fornecedores": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Fornecedor"
                ],
                "summary": "List Fornecedores",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by nome using operators: like, ilike, eq, ne. Format: operator.value (e.g. like.João)",
                        "name": "filter-nome",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by cnpj using operators: eq, ne, like, ilike. Format: operator.value (e.g. eq.123456789)",
                        "name": "filter-cnpj",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort fields: nome, cnpj. Prefix with '-' for desc. Comma separated for multiple fields (e.g. -nome,cnpj)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination limit (default 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Fornecedor"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Fornecedor"
                ],
                "summary": "Create Fornecedor",
                "parameters": [
                    {
                        "description": "Fornecedor payload",
                        "name": "fornecedor",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.FornecedorCreate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Fornecedor"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/fornecedores/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Fornecedor"
                ],
                "summary": "Get Fornecedor by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Fornecedor ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Fornecedor"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Fornecedor"
                ],
                "summary": "Update Fornecedor",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Fornecedor ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fornecedor payload",
                        "name": "fornecedor",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.FornecedorCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Fornecedor"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Fornecedor"
                ],
                "summary": "Delete Fornecedor",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Fornecedor ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Fornecedor"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the health status of the application and dependencies.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Server"
                ],
                "summary": "Check health of the system",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/produtos": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Produtos"
                ],
                "summary": "List Produtos (all types)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by nome. Format: \u003cop\u003e.\u003cvalue\u003e. Ops: like, ilike, eq, ne",
                        "name": "filter-nome",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by categoria. Format: \u003cop\u003e.\u003cvalue\u003e. Ops: like, ilike, eq, ne",
                        "name": "filter-categoria",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by marca. Format: \u003cop\u003e.\u003cvalue\u003e. Ops: like, ilike, eq, ne",
                        "name": "filter-marca",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort by attribute. Allowed: nome, categoria, marca. Prefix '-' for desc. Comma separated",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination limit (default 0)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.UnionProduto"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Produtos"
                ],
                "summary": "Create Produto",
                "parameters": [
                    {
                        "description": "Product payload",
                        "name": "produto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ProdutoCreate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Produto"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/produtos/comercial": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Produtos"
                ],
                "summary": "List Comercial products",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by nome. Format: \u003cop\u003e.\u003cvalue\u003e. Ops: like, ilike, eq, ne",
                        "name": "filter-nome",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by categoria. Format: \u003cop\u003e.\u003cvalue\u003e. Ops: like, ilike, eq, ne",
                        "name": "filter-categoria",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by marca. Format: \u003cop\u003e.\u003cvalue\u003e. Ops: like, ilike, eq, ne",
                        "name": "filter-marca",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Filter by preco_venda. Format: \u003cop\u003e.\u003cvalue\u003e. Ops: eq, ne, lt, gt, le, ge",
                        "name": "filter-preco_venda",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort fields: nome, categoria, marca, preco_venda. Prefix '-' for desc. Comma separated",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination limit (default 0)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Comercial"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Produtos"
                ],
                "summary": "Create Comercial Produto",
                "parameters": [
                    {
                        "description": "Comercial product payload",
                        "name": "produto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ComercialCreate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Comercial"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/produtos/comercial/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Produtos"
                ],
                "summary": "Get Comercial Produto by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Produto ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Comercial"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Produtos"
                ],
                "summary": "Update Comercial Produto",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Produto ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Comercial product payload",
                        "name": "produto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ComercialCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Comercial"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/produtos/estrutural": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Produtos"
                ],
                "summary": "List Estrutural products",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by nome. Format: \u003cop\u003e.\u003cvalue\u003e. Ops: like, ilike, eq, ne",
                        "name": "filter-nome",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by categoria. Format: \u003cop\u003e.\u003cvalue\u003e. Ops: like, ilike, eq, ne",
                        "name": "filter-categoria",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by marca. Format: \u003cop\u003e.\u003cvalue\u003e. Ops: like, ilike, eq, ne",
                        "name": "filter-marca",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort fields: nome, categoria, marca. Prefix '-' for desc. Comma separated",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination limit (default 0)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Produto"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/produtos/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Produtos"
                ],
                "summary": "Get Produto by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Produto ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Produto"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Produtos"
                ],
                "summary": "Update Produto",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Produto ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Product payload",
                        "name": "produto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ProdutoCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Produto"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Produtos"
                ],
                "summary": "Delete Produto",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Produto ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Comercial": {
            "type": "object",
            "properties": {
                "categoria": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "marca": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "preco_venda": {
                    "type": "number"
                }
            }
        },
        "model.ComercialCreate": {
            "type": "object",
            "properties": {
                "categoria": {
                    "type": "string"
                },
                "marca": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "preco_venda": {
                    "type": "number"
                }
            }
        },
        "model.Fornecedor": {
            "type": "object",
            "properties": {
                "cnpj": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                }
            }
        },
        "model.FornecedorCreate": {
            "type": "object",
            "properties": {
                "cnpj": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                }
            }
        },
        "model.Produto": {
            "type": "object",
            "properties": {
                "categoria": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "marca": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                }
            }
        },
        "model.ProdutoCreate": {
            "type": "object",
            "properties": {
                "categoria": {
                    "type": "string"
                },
                "marca": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                }
            }
        },
        "model.UnionProduto": {
            "type": "object",
            "properties": {
                "categoria": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "marca": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "preco_venda": {
                    "type": "number"
                }
            }
        },
        "types.ErrorResponse": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "EDNA Bar System",
	Description:      "Aplicação de Banco de Dados para Gerenciamento de Bares",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
