// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Returns a 404 JSON response for unmatched routes.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Server"
                ],
                "summary": "Unmatched path handler",
                "responses": {
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/clientes": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cliente"
                ],
                "summary": "List Clients",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by nome using operators: like, ilike, eq, ne. Format: operator.value (e.g. like.João)",
                        "name": "filter-nome",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by cnpj using operators: eq, ne, like, ilike. Format: operator.value (e.g. eq.123456789)",
                        "name": "filter-cnpj",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort fields: nome, cnpj. Prefix with '-' for desc. Comma separated for multiple fields (e.g. -nome,cnpj)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination limit (default 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Cliente"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cliente"
                ],
                "summary": "Create Cliente",
                "parameters": [
                    {
                        "description": "Cliente payload",
                        "name": "fornecedor",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ClienteCreate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Cliente"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/clientes/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cliente"
                ],
                "summary": "Get Cliente by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Cliente ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Cliente"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cliente"
                ],
                "summary": "Update Cliente",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Cliente ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Cliente payload",
                        "name": "fornecedor",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ClienteCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Cliente"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cliente"
                ],
                "summary": "Delete Cliente",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Cliente ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Cliente"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/fornecedores": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Fornecedor"
                ],
                "summary": "List Fornecedores",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by nome using operators: like, ilike, eq, ne. Format: operator.value (e.g. like.João)",
                        "name": "filter-nome",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by cnpj using operators: eq, ne, like, ilike. Format: operator.value (e.g. eq.123456789)",
                        "name": "filter-cnpj",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort fields: nome, cnpj. Prefix with '-' for desc. Comma separated for multiple fields (e.g. -nome,cnpj)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination limit (default 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Fornecedor"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Fornecedor"
                ],
                "summary": "Create Fornecedor",
                "parameters": [
                    {
                        "description": "Fornecedor payload",
                        "name": "fornecedor",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.FornecedorCreate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Fornecedor"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/fornecedores/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Fornecedor"
                ],
                "summary": "Get Fornecedor by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Fornecedor ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Fornecedor"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Fornecedor"
                ],
                "summary": "Update Fornecedor",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Fornecedor ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fornecedor payload",
                        "name": "fornecedor",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.FornecedorCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Fornecedor"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Fornecedor"
                ],
                "summary": "Delete Fornecedor",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Fornecedor ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Fornecedor"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/funcionarios": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Funcionario"
                ],
                "summary": "List Funcionarios",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by nome using operators: like, ilike, eq, ne. Format: operator.value (e.g. like.João)",
                        "name": "filter-nome",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by CPF using operators: eq, ne, like, ilike. Format: operator.value (e.g. eq.123456789)",
                        "name": "filter-CPF",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort fields: nome, CPF. Prefix with '-' for desc. Comma separated for multiple fields (e.g. -nome,CPF)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination limit (default 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Funcionario"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Funcionario"
                ],
                "summary": "Create Funcionario",
                "parameters": [
                    {
                        "description": "Funcionario payload",
                        "name": "funcionario",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.FuncionarioCreate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Funcionario"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/funcionarios/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Funcionario"
                ],
                "summary": "Get Funcionario by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Funcionario ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Funcionario"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Funcionario"
                ],
                "summary": "Update Funcionario",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Funcionario ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Funcionario payload",
                        "name": "funcionario",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.FuncionarioCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Funcionario"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Funcionario"
                ],
                "summary": "Delete Funcionario",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Funcionario ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Funcionario"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the health status of the application and dependencies.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Server"
                ],
                "summary": "Check health of the system",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/lotes": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lote"
                ],
                "summary": "List Lotes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by nome using operators: like, ilike, eq, ne. Format: operator.value (e.g. like.João)",
                        "name": "filter-nome",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by cnpj using operators: eq, ne, like, ilike. Format: operator.value (e.g. eq.123456789)",
                        "name": "filter-cnpj",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort fields: nome, cnpj. Prefix with '-' for desc. Comma separated for multiple fields (e.g. -nome,cnpj)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination limit (default 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Lote"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lote"
                ],
                "summary": "Create Lote",
                "parameters": [
                    {
                        "description": "Lote payload",
                        "name": "fornecedor",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LoteCreate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Lote"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lotes/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lote"
                ],
                "summary": "Get Lote by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Lote ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Lote"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lote"
                ],
                "summary": "Update Lote",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Lote ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Lote payload",
                        "name": "fornecedor",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LoteCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Lote"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lote"
                ],
                "summary": "Delete Lote",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Lote ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Lote"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ofertas": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Oferta"
                ],
                "summary": "List Ofertas",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by nome using operators: like, ilike, eq, ne. Format: operator.value (e.g. like.João)",
                        "name": "filter-nome",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by cnpj using operators: eq, ne, like, ilike. Format: operator.value (e.g. eq.123456789)",
                        "name": "filter-cnpj",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort fields: nome, cnpj. Prefix with '-' for desc. Comma separated for multiple fields (e.g. -nome,cnpj)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination limit (default 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Oferta"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Oferta"
                ],
                "summary": "Create Oferta",
                "parameters": [
                    {
                        "description": "Oferta payload",
                        "name": "fornecedor",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.OfertaCreate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Oferta"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ofertas/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Oferta"
                ],
                "summary": "Get Oferta by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Oferta ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Oferta"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Oferta"
                ],
                "summary": "Update Oferta",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Oferta ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Oferta payload",
                        "name": "fornecedor",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.OfertaCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Oferta"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Oferta"
                ],
                "summary": "Delete Oferta",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Oferta ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Oferta"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/produtos": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Produtos"
                ],
                "summary": "List Produtos (all types)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by nome. Format: \u003cop\u003e.\u003cvalue\u003e. Ops: like, ilike, eq, ne",
                        "name": "filter-nome",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by categoria. Format: \u003cop\u003e.\u003cvalue\u003e. Ops: like, ilike, eq, ne",
                        "name": "filter-categoria",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by marca. Format: \u003cop\u003e.\u003cvalue\u003e. Ops: like, ilike, eq, ne",
                        "name": "filter-marca",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort by attribute. Allowed: nome, categoria, marca. Prefix '-' for desc. Comma separated",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination limit (default 0)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.UnionProduto"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Produtos"
                ],
                "summary": "Create Produto",
                "parameters": [
                    {
                        "description": "Product payload",
                        "name": "produto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ProdutoCreate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Produto"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/produtos/comercial": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Produtos"
                ],
                "summary": "List Comercial products",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by nome. Format: \u003cop\u003e.\u003cvalue\u003e. Ops: like, ilike, eq, ne",
                        "name": "filter-nome",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by categoria. Format: \u003cop\u003e.\u003cvalue\u003e. Ops: like, ilike, eq, ne",
                        "name": "filter-categoria",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by marca. Format: \u003cop\u003e.\u003cvalue\u003e. Ops: like, ilike, eq, ne",
                        "name": "filter-marca",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Filter by preco_venda. Format: \u003cop\u003e.\u003cvalue\u003e. Ops: eq, ne, lt, gt, le, ge",
                        "name": "filter-preco_venda",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort fields: nome, categoria, marca, preco_venda. Prefix '-' for desc. Comma separated",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination limit (default 0)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Comercial"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Produtos"
                ],
                "summary": "Create Comercial Produto",
                "parameters": [
                    {
                        "description": "Comercial product payload",
                        "name": "produto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ComercialCreate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Comercial"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/produtos/comercial/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Produtos"
                ],
                "summary": "Get Comercial Produto by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Produto ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Comercial"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Produtos"
                ],
                "summary": "Update Comercial Produto",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Produto ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Comercial product payload",
                        "name": "produto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ComercialCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Comercial"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/produtos/estrutural": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Produtos"
                ],
                "summary": "List Estrutural products",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by nome. Format: \u003cop\u003e.\u003cvalue\u003e. Ops: like, ilike, eq, ne",
                        "name": "filter-nome",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by categoria. Format: \u003cop\u003e.\u003cvalue\u003e. Ops: like, ilike, eq, ne",
                        "name": "filter-categoria",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by marca. Format: \u003cop\u003e.\u003cvalue\u003e. Ops: like, ilike, eq, ne",
                        "name": "filter-marca",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort fields: nome, categoria, marca. Prefix '-' for desc. Comma separated",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination limit (default 0)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Produto"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/produtos/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Produtos"
                ],
                "summary": "Get Produto by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Produto ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Produto"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Produtos"
                ],
                "summary": "Update Produto",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Produto ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Product payload",
                        "name": "produto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ProdutoCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Produto"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Produtos"
                ],
                "summary": "Delete Produto",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Produto ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vendas": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Venda"
                ],
                "summary": "List Vendas",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Filter by idCliente using operators: eq, ne, gt, lt",
                        "name": "filter-idCliente",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by idFuncionario using operators: eq, ne, gt, lt",
                        "name": "filter-idFuncionario",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by tipoPagamento using operators: eq, ne, like, ilike",
                        "name": "filter-tipoPagamento",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by dataHoraVenda using operators: eq, ne, gt, lt",
                        "name": "filter-dataHoraVenda",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort fields: dataHoraVenda, dataHoraPagamento, tipoPagamento. Prefix with '-' for desc.",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination limit (default 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Venda"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Venda"
                ],
                "summary": "Create Venda",
                "parameters": [
                    {
                        "description": "Venda payload",
                        "name": "venda",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.VendaCreate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Venda"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vendas/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Venda"
                ],
                "summary": "Get Venda by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Venda ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Venda"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Venda"
                ],
                "summary": "Update Venda",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Venda ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Venda payload",
                        "name": "venda",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.VendaCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Venda"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Venda"
                ],
                "summary": "Delete Venda",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Venda ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Venda"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Cliente": {
            "type": "object",
            "properties": {
                "cpf": {
                    "type": "string"
                },
                "data_nascimento": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                }
            }
        },
        "model.ClienteCreate": {
            "type": "object",
            "properties": {
                "cpf": {
                    "type": "string"
                },
                "data_nascimento": {
                    "description": "Espera-se \"YYYY-MM-DD\" ou formato RFC3339",
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                }
            }
        },
        "model.Comercial": {
            "type": "object",
            "properties": {
                "categoria": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "marca": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "preco_venda": {
                    "type": "number"
                }
            }
        },
        "model.ComercialCreate": {
            "type": "object",
            "properties": {
                "categoria": {
                    "type": "string"
                },
                "marca": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "preco_venda": {
                    "type": "number"
                }
            }
        },
        "model.Fornecedor": {
            "type": "object",
            "properties": {
                "cnpj": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                }
            }
        },
        "model.FornecedorCreate": {
            "type": "object",
            "properties": {
                "cnpj": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                }
            }
        },
        "model.Funcionario": {
            "type": "object",
            "properties": {
                "CPF": {
                    "type": "string"
                },
                "data_contratacao": {
                    "type": "string"
                },
                "expediente": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                },
                "salario": {
                    "type": "number"
                },
                "tipo": {
                    "type": "string"
                }
            }
        },
        "model.FuncionarioCreate": {
            "type": "object",
            "properties": {
                "CPF": {
                    "type": "string"
                },
                "data_contratacao": {
                    "type": "string"
                },
                "expediente": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "salario": {
                    "type": "number"
                },
                "tipo": {
                    "type": "string"
                }
            }
        },
        "model.Lote": {
            "type": "object",
            "properties": {
                "data_fornecimento": {
                    "type": "string"
                },
                "estragados": {
                    "type": "integer"
                },
                "id_fornecedor": {
                    "type": "integer"
                },
                "id_lote": {
                    "type": "integer"
                },
                "id_produto": {
                    "type": "integer"
                },
                "preco_unitario": {
                    "type": "number"
                },
                "quantidade_inicial": {
                    "type": "integer"
                },
                "validade": {
                    "type": "string"
                }
            }
        },
        "model.LoteCreate": {
            "type": "object",
            "properties": {
                "data_fornecimento": {
                    "type": "string"
                },
                "estragados": {
                    "type": "integer"
                },
                "id_fornecedor": {
                    "type": "integer"
                },
                "id_produto": {
                    "type": "integer"
                },
                "preco_unitario": {
                    "type": "number"
                },
                "quantidade_inicial": {
                    "type": "integer"
                },
                "validade": {
                    "type": "string"
                }
            }
        },
        "model.Oferta": {
            "type": "object",
            "properties": {
                "data_criacao": {
                    "type": "string"
                },
                "data_fim": {
                    "type": "string"
                },
                "data_inicio": {
                    "type": "string"
                },
                "id_oferta": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                },
                "percentual_desconto": {
                    "type": "integer"
                },
                "valor_fixo": {
                    "type": "number"
                }
            }
        },
        "model.OfertaCreate": {
            "type": "object",
            "properties": {
                "data_fim": {
                    "type": "string"
                },
                "data_inicio": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "percentual_desconto": {
                    "type": "integer"
                },
                "valor_fixo": {
                    "type": "number"
                }
            }
        },
        "model.Produto": {
            "type": "object",
            "properties": {
                "categoria": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "marca": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                }
            }
        },
        "model.ProdutoCreate": {
            "type": "object",
            "properties": {
                "categoria": {
                    "type": "string"
                },
                "marca": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                }
            }
        },
        "model.UnionProduto": {
            "type": "object",
            "properties": {
                "categoria": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "marca": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "preco_venda": {
                    "type": "number"
                }
            }
        },
        "model.Venda": {
            "type": "object",
            "properties": {
                "data_hora_pagamento": {
                    "type": "string"
                },
                "data_hora_renda": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "id_cliente": {
                    "type": "integer"
                },
                "id_funcionario": {
                    "type": "integer"
                },
                "tipo_pagamento": {
                    "type": "string"
                }
            }
        },
        "model.VendaCreate": {
            "type": "object",
            "properties": {
                "data_hora_pagamento": {
                    "type": "string"
                },
                "data_hora_renda": {
                    "type": "string"
                },
                "id_cliente": {
                    "type": "integer"
                },
                "id_funcionario": {
                    "type": "integer"
                },
                "tipo_pagamento": {
                    "type": "string"
                }
            }
        },
        "types.ErrorResponse": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "EDNA Bar System",
	Description:      "Aplicação de Banco de Dados para Gerenciamento de Bares",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
